### ISSUE TITLE
Multiple select and/with input group

### ISSUE THREAD

**Issue by wselen** [apalfrey/select2-bootstrap-5-theme#53]
Using multiple select the input box is too high compared to others because the search inline is on the next line.
Would be nice if this would work like bootstrap 3, inline next too tags.

With these adjustment I could fix it for now :

// fix: input-group

           .input-group > .select2-container--bootstrap-5 {
                width: auto !important;
            }

// fix: multiple select
            .select2-selection--multiple {
                padding: 0 !important;
            }
            .select2-selection--multiple > ul {
                display: inline-flex !important;
            }
            .select2-selection--multiple > ul > li {
                padding: 0 0.3rem !important;
                margin: 0.3rem !important;
            }
            .select2-selection--multiple .select2-search--inline {
                display: inline-flex !important;
                width: auto !important;
                margin-top: 0.3rem !important;
                vertical-align: middle;
            }

![image](https://user-images.githubusercontent.com/33697376/141349448-a2dcd7c6-c991-4490-93a9-f21aaab5f94f.png)

**Comment by hdogan** [comment]
It works but it cuts placeholder text...

**Comment by apalfrey** [comment]
> It works but it also cuts placeholder text and removes placeholder padding...

This is exactly why I made the decision to have the fields on a separate line to the tags. It caused a lot of issues and was simpler, more effective and didn't break the layout as much having it on a separate line.

I'll keep this open to see what people think but I'm inclined to keep the field on a separate line to the tags

**Comment by ceab254** [comment]
This fix with jQuery still solves the problem with the placeholder.

CSS
``` css
/*fix: multiple select*/
.select2-selection--multiple {
    padding: 0rem 0.75rem !important;
}
.select2-selection--multiple > ul {
    display: inline-flex !important;
}
.select2-selection--multiple > ul > li {
    padding: 0 0.3rem !important;
    margin: 0.3rem !important;
}
.select2-selection--multiple .select2-search--inline {
    display: inline-flex !important;
    width: auto !important;
    margin-top: 0.3rem !important;
    vertical-align: middle;
}
```

JavaScript / jQuery
```javascript
$('select[multiple]').on('select2:select select2:unselect change', function () {
    $(this).next().find('.select2-selection--multiple')
        .attr('style', ('padding: ' + ($(this).val().length ? 0 : '0rem 0.75rem') + '!important'));
});
```

Thanks for your help guys 👍
