### ISSUE TITLE
The magnifying glass image and the CSS to display it seem to be missing from all the v4 e v5 themes. 

### ISSUE THREAD

**Issue by fulviocanducci** [apalfrey/select2-bootstrap-5-theme#68]
Ref: https://github.com/select2/select2/issues/4629#issuecomment-312771486

I miss this feature too. The magnifying glass image and the CSS to display it seem to be missing from all the v4 themes. My workaround was to lift select2.png and select2x2.png from the v3 files and insert the following CSS into my application:

```css
.select2-container--default .select2-search--dropdown .select2-search__field {
  background: url(select2.png) right top no-repeat;
  background-position: right -22px;
}

@media only screen and (-webkit-min-device-pixel-ratio: 1.5), only screen and (min-resolution: 2dppx)  {
   .select2-container--default .select2-search--dropdown .select2-search__field {
      background-image: url(select2x2.png);
      background-repeat: no-repeat;
      background-size: 60px 40px;
      background-position: 100% -21px;
   }
}
```

![select2](https://user-images.githubusercontent.com/1295900/27813931-e3c4e004-60ab-11e7-8d86-89fb90d23993.png)
![select2x2](https://user-images.githubusercontent.com/1295900/27813936-ebe5526e-60ab-11e7-9010-9b8f47e8342e.png)

I notice that some people have made their own themes that put the icon back. For example, this Yii2 integration:
http://demos.krajee.com/widget-details/select2

_Originally posted by @rohanc in https://github.com/select2/select2/issues/4629#issuecomment-312771486_
