### ISSUE TITLE
With a multiple select, the search input isn't actually inline (ie it breaks onto it's own line)

### ISSUE THREAD

**Issue by hobailey** [apalfrey/select2-bootstrap-5-theme#86]
## The issue
When using this theme on a multiple select, the search input is always on it's own line (and never along side/inline the selected values):
<img width="222" alt="image" src="https://github.com/apalfrey/select2-bootstrap-5-theme/assets/1564439/4494d8b1-46f9-473f-bb2d-92bf1be1a8a6">

The v4 theme doesn't have this issue though (see demo [here](https://select2.github.io/select2-bootstrap-theme/4.0.3.html)):
<img width="292" alt="image" src="https://github.com/apalfrey/select2-bootstrap-5-theme/assets/1564439/3c5db8b2-3949-4169-84d2-b963be3752ce">

Note that this is separate/different from the issue when using prepends etc (https://github.com/apalfrey/select2-bootstrap-5-theme/pull/79).

## Code and demo of issue
[Here](https://jsfiddle.net/cn0q1zm4/)

## Expected behaviour
The search input is on the same line/level as the selected values and only goes onto a new line when there is insufficient space

**Comment by nicojmb** [comment]
same issue here, any news?

**Comment by ozonerik** [comment]
same issues

**Comment by nicojmb** [comment]
It's project die?

**Comment by petemarvin** [comment]
You may try this css: https://github.com/apalfrey/select2-bootstrap-5-theme/issues/53#issuecomment-1322289723

.select2-container--bootstrap-5 .select2-selection--multiple .select2-selection__rendered {
    display: inline;
}
	   
.select2-container--bootstrap-5 .select2-selection--multiple .select2-selection__rendered .select2-selection__choice {
    display: inline-flex;
}
	   
.select2-container--bootstrap-5 .select2-selection--multiple .select2-search {
    display: inline;
}

**Comment by nicojmb** [comment]
> You may try this css: [#53 (comment)](https://github.com/apalfrey/select2-bootstrap-5-theme/issues/53#issuecomment-1322289723)
> 
> .select2-container--bootstrap-5 .select2-selection--multiple .select2-selection__rendered { display: inline; }
> 
> .select2-container--bootstrap-5 .select2-selection--multiple .select2-selection__rendered .select2-selection__choice { display: inline-flex; }
> 
> .select2-container--bootstrap-5 .select2-selection--multiple .select2-search { display: inline; }

Perfect, with this code fix it!!

![image](https://github.com/user-attachments/assets/1a365053-6541-4a66-8a56-cf8f6d5a4dd5)

**Comment by Martin12350** [comment]
Voting for option in the settings to have search bar on the same line ;)
I also did not like the uneven space on top and bottom because of that margin on child items.

**Not modified (suggested) css** - notice the space below items
![image](https://github.com/user-attachments/assets/e597ddb5-83ff-4d46-911a-0d3079f9aed2)

Here is my modification of the previous CSS.
```css
.select2-container--bootstrap-5 .select2-selection--multiple .select2-selection__rendered {
	display: inline-flex;
	flex-wrap: wrap;
	gap: .3em .65em;
}
.select2-container--bootstrap-5 .select2-selection--multiple .select2-selection__rendered .select2-selection__choice {
	display: inline-flex;
	margin: .15em 0;
}
.select2-container--bootstrap-5 .select2-selection--multiple .select2-search {
	display: inline;
}
.select2-container--bootstrap-5 .select2-selection--multiple .select2-selection__rendered .select2-selection__choice:last-child {
	margin-right: .65em;
}
.select2-container--bootstrap-5 .select2-selection--multiple .select2-search .select2-search__field {
	margin-top: .2em;
}
/* this ugly piece of style here allows us to hide the search bar (empty row) if we have no focus on the select, but still allow tab on it, while preserving the placeholder if no choices are selected */
.select2-container--bootstrap-5:not(.select2-container--focus) .select2-selection--multiple .select2-selection__rendered:has(.select2-selection__choice) + .select2-search {
	display: inline-block;
	width: 0;
	height: 0;
	overflow: hidden;
}
```

**Without focus**
![image](https://github.com/user-attachments/assets/2d03975f-6c81-4562-87ab-6e0426b0a974)

**With focus**
![image](https://github.com/user-attachments/assets/15235afd-3465-4d2c-a087-031fbbb5d80e)

This is not perfect, but seems better, at least in my eyes :)
